apiVersion: apps/v1 # version de kubernetes
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: python-app
    template:
      metadata:
        labels:
          app: python-app
      spec:
        containers:
        - name: python-app
          image: matiasolivar/py-app:latest   # Example of image used 
          ports:
            - containerPort: 6000