apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app
  namespace: web-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  